services:
  app:
    image: ruby:3.3
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tmpfs:
      - /tmp
    command: bundle exec ruby main.rb

volumes:
  bundle:
